FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .

RUN npm run build

FROM nginx:alpine

# Copia el build de React
COPY --from=builder /app/dist /usr/share/nginx/html

# Sobrescribe la config por defecto de nginx con el reverse proxy hacia el backend
COPY nginx.prod.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
