services:
  frontend:
    image: hospital-frontend:${FRONTEND_IMAGE_TAG:-devel}
    container_name: ${FRONTEND_CONTAINER_NAME:-hospital-frontend}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_HOST_PORT:-5173}:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true